package edu.bu.cs622.mode;

import edu.bu.cs622.path.Path;
import edu.bu.cs622.path.Step;
import java.util.List;

/**
 * This is the DifficultMode class.
 * This class is responsible for representing a DifficultMode.
 */
public class DifficultMode implements Mode {

  /**
   * Validate the path in difficult mode. Verify both directions and colors.
   * 
   * @param gamePath The random path generated by the game
   * @param userPath The user input path
   * @return Return true if the user input path is the same as the game generated
   */
  @Override
  public boolean validatePath(Path gamePath, Path userPath) {
    List<Step> gameSteps = gamePath.getSteps();
    List<Step> userSteps = userPath.getSteps();

    for (int i = 0; i < gameSteps.size(); i++) {
      if (!gameSteps.get(i).getDirection().equals(userSteps.get(i).getDirection())) {
        return false;
      }
      if (!gameSteps.get(i).getColor().equals(userSteps.get(i).getColor())) {
        return false;
      }
    }

    return true;
  }

}
